-- vim.cmd [[
--     imap <silent><script><expr> <C-A> copilot#Accept("\<CR>")
--     let g:copilot_no_tab_map = v:true
-- ]]
--
-- vim.cmd [[
-- let g:copilot_filetypes = {
--       \ '*': v:false,
--       \ 'rust': v:true,
--       \ }
-- ]]
